GEODE-1613 CI failure: ConnectionPoolDUnitTest.test021ClientGetOfInvalidServerEntry

Added a try/catch for scheduling the task to handle RejectedExecutionException
& fixed up the handling of shutdown conditions so the run() method no longer
throws cancellation exceptions.

-      if(pool.getCancelCriterion().cancelInProgress() != null) {
+      if (pool.getCancelCriterion().cancelInProgress() != null) {
+      
+      
+      
-          pool.getCancelCriterion().checkCancelInProgress(e);
-          throw e;
+          if (pool.getCancelCriterion().cancelInProgress() == null) {
+            throw e;
+          }
-          throw e;
+          return;
-          pool.getCancelCriterion().checkCancelInProgress(e);
-          throw e; // weird
+          if (pool.getCancelCriterion().cancelInProgress() == null) {
+            throw e; // weird
+          }
-          pool.getCancelCriterion().checkCancelInProgress(e);
+          if (pool.getCancelCriterion().cancelInProgress() != null) {
+            return;
+          }
-            background.schedule(new RecoveryTask(), pingInterval, TimeUnit.MILLISECONDS);
-            recoveryScheduled = true;
+            try {
+              background.schedule(new RecoveryTask(), pingInterval, TimeUnit.MILLISECONDS);
+              recoveryScheduled = true;
+            } catch (RejectedExecutionException ex) { // GEODE-1613 - suspect string while shutting down
+              if (!background.isTerminated()
+                  && pool.getCancelCriterion().cancelInProgress() == null) {
+                throw ex;
+              }
+            }
+
