OPENNLP-525: Exception cleanup in opennlp-tools. Thanks to Daniel Naber for the patch.

git-svn-id: https://svn.apache.org/repos/asf/opennlp/trunk@1363429 13f79535-47bb-0310-9956-ffa450edef68

-      throw new TerminateToolException(-1, "IO error while reading training data or indexing data: " + e.getMessage());
+      throw new TerminateToolException(-1, "IO error while reading training data or indexing data: "
+          + e.getMessage(), e);
-    } catch (IOException ex) {
-      throw new TerminateToolException(-1, "IO error while writing dictionary file: " + ex.getMessage());
+    } catch (IOException e) {
+      throw new TerminateToolException(-1, "IO error while writing dictionary file: "
+          + e.getMessage(), e);
-          throw new TerminateToolException(-1, "Attention: Failed to correctly write dictionary:" + e.getMessage());
+          throw new TerminateToolException(-1, "Attention: Failed to correctly write dictionary:" +
+              e.getMessage(), e);

UPD42 INS42 INS42 UPD42 INS42