YARN-634. Modified YarnRemoteException to be not backed by PB and introduced a separate SerializedException record. Contributed by Siddharth Seth.
MAPREDUCE-5239. Updated MR App to reflect YarnRemoteException changes after YARN-634. Contributed by Siddharth Seth.


git-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1481205 13f79535-47bb-0310-9956-ffa450edef68

-import org.apache.hadoop.conf.Configuration;
-import org.apache.hadoop.yarn.exceptions.impl.pb.YarnRemoteExceptionPBImpl;
-import org.apache.hadoop.yarn.factories.YarnRemoteExceptionFactory;
-import org.apache.hadoop.yarn.factory.providers.YarnRemoteExceptionFactoryProvider;
-
-   * Relying on the default factory configuration to be set correctly
-   * for the default configuration.
-   */
-  private static Configuration conf = new Configuration();
-  private static YarnRemoteExceptionFactory exceptionFactory = YarnRemoteExceptionFactoryProvider.getYarnRemoteExceptionFactory(conf);
-  
-  /**
-   * Returns the YarnRemoteException which is serializable. 
+   * Returns an instance of YarnRemoteException 
-    return exceptionFactory.createYarnRemoteException(t);
+    return new YarnRemoteException(t);
-   * Returns the YarnRemoteException which is serializable.
+   * Returns an instance of YarnRemoteException
-    return exceptionFactory.createYarnRemoteException(message);
+    return new YarnRemoteException(message);
-  public static String toString(YarnRemoteException e) {
-    return (e.getMessage() == null ? "" : e.getMessage()) + 
-      (e.getRemoteTrace() == null ? "" : "\n StackTrace: " + e.getRemoteTrace()) + 
-      (e.getCause() == null ? "" : "\n Caused by: " + toString(e.getCause()));
-  }
-  
-          throw ((RemoteException) se.getCause())
-              .unwrapRemoteException(YarnRemoteExceptionPBImpl.class);
+          // TODO Fix in YARN-628.
+          throw new IOException((RemoteException) se.getCause());
