YARN-9486. Docker container exited with failure does not get clean up correctly. Contributed by Eric Yang

-      pidFilePath = getPidFilePath(appIdStr, containerIdStr);
+      try {
+        // try to locate existing pid file.
+        pidFilePath = getPidFilePath(appIdStr, containerIdStr);
+      } catch (IOException e) {
+        // reset pid file path if it did not exist.
+        String pidFileSubpath = getPidFileSubpath(appIdStr, containerIdStr);
+        pidFilePath = dirsHandler.getLocalPathForWrite(pidFileSubpath);
+      }

INS54 INS8 INS12 MOV21 INS44 INS8 INS43 INS42 INS60 INS21 INS42 INS43 INS59 INS7 INS42 INS42 INS32 INS42 INS32 INS42 INS42 INS42 INS42 INS42 INS42