HDFS-4581. DataNode.checkDiskError should not be called on network errors. Contributed by Rohit Kochar.

git-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1461597 13f79535-47bb-0310-9956-ffa450edef68

+import java.net.SocketException;
+import java.net.SocketTimeoutException;
+import java.nio.channels.ClosedByInterruptException;
-    
+    if (e instanceof SocketException || e instanceof SocketTimeoutException
+    	  || e instanceof ClosedByInterruptException 
+    	  || e.getMessage().startsWith("Broken pipe")) {
+      LOG.info("Not checking disk as checkDiskError was called on a network" +
+      		" related exception");	
+      return;
+    }
-        // check if there are any disk problem
-        checkDiskError();
+          // check if there are any disk problem
+        try{
+          checkDiskError(ie);
+        } catch(IOException e) {
+            LOG.warn("DataNode.checkDiskError failed in run() with: ", e);
+        }

INS26 INS26 INS26 INS40 INS40 INS40 INS25 INS27 INS8 INS62 INS62 INS62 INS32 INS21 INS41 INS42 INS43 INS42 INS43 INS42 INS43 INS32 INS42 INS45 INS32 INS42 INS42 INS42 INS42 INS42 INS42 INS42 INS27 INS54 INS45 INS45 INS8 INS12 MOV21 INS44 INS8 INS43 INS42 INS21 INS42 INS42 INS32 INS42 INS42 INS45 INS42